pipeline:
  name: test-iacM-uk
  identifier: testiacMuk
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: iac-tf-stage
        identifier: iactfstage
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: test_myvm_uk
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  spec:
                    command: init
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: Validate
                  identifier: Validate
                  spec:
                    command: validate
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  spec:
                    command: plan
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: Apply
                  identifier: apply
                  spec:
                    command: apply
                  timeout: 10m
                  when:
                    stageStatus: Success
                    condition: <+pipeline.branch> == "main"
        tags: {}
        variables:
          - name: instance_name
            type: String
            description: ""
            required: true
            value: <+input>
          - name: region
            type: String
            description: ""
            required: false
            value: <+input>
          - name: instance_type
            type: String
            description: ""
            required: false
            value: <+input>
          - name: zone
            type: String
            description: ""
            required: false
            value: <+input>
