pipeline:
  name: test-iacM-uk
  identifier: testiacMuk
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: iac-tf-stage
        identifier: iactfstage
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: myvminfrauk
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  spec:
                    command: init
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  spec:
                    command: plan
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: Destroy
                  identifier: Destroy
                  spec:
                    command: apply
                  timeout: 10m
        tags: {}
