pipeline:
  name: test-iacM-uk
  identifier: testiacMuk
  projectIdentifier: ORCA_onedev
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: iac-tf-stage
        identifier: iactfstage
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: test_myvm_uk
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  spec:
                    command: init
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  spec:
                    command: plan
                  timeout: 10m
              - step:
                  type: Run
                  name: Debug Branch
                  identifier: Debug_Branch
                  spec:
                    shell: Sh
                    command: "echo \"Branch: <+pipeline.branch>\""
              - step:
                  type: IACMTerraformPlugin
                  name: Apply
                  identifier: apply
                  spec:
                    command: apply
                  skipCondition: <+codebase.branch != 'main'>
                  timeout: 10m
        tags: {}
